# -*- coding: utf-8 -*-
"""NLP_LM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gH3ZlA9HDbmOMHUw90_lhvh_Gq5gpjUl

**🧠 AI-Driven NLP Project — GPT-2 & BERT**

**Final Submission (Research-Grade)**


---



**Models:** GPT-2 (Text Generation) + BERT (Language Understanding)

**Environment:** Google Colab (GPU — T4 or A100)


---



**📋 Table of Contents **

1.Environment Setup & Installation

2.LM Selection & Justification

3.GPT-2 Implementation

4.BERT Implementation

5.Exploration & Analysis

6.Dataset-Based Evaluation — IMDb Sentiment Analysis ⬅️ NEW

7.Performance Analysis — Latency Comparison ⬅️ NEW

8.Research Questions & Final Answers ⬅️ UPDATED

9.Statistical Validation

10.Advanced Metrics — BLEU / ROUGE / F1

11.Attention Visualization (BERT)

12.Failure Case Analysis

13.Baseline Model Comparison

14.Visualization of Results

15.Real-World Applications

16.Ethics & Alignment

17.Final Conclusion & Insights ⬅️ UPDATED


---
"""



"""**Section 1: Environment Setup &** **Installation**

"""

# ============================================================
# SECTION 1: Install Dependencies
# ============================================================
!pip install -q transformers torch datasets matplotlib seaborn wordcloud
!pip install -q bertviz scikit-learn pandas numpy tqdm
!pip install -q accelerate sentencepiece rouge-score nltk
print("✅ All packages installed successfully!")

# ============================================================
# Core Imports
# ============================================================
import torch, numpy as np, pandas as pd
import matplotlib.pyplot as plt, matplotlib.patches as mpatches
import seaborn as sns, warnings, time, re
from collections import Counter
from wordcloud import WordCloud
warnings.filterwarnings('ignore')

# HuggingFace
from transformers import (
    GPT2LMHeadModel, GPT2Tokenizer,
    BertForMaskedLM, BertTokenizer,
    BertForSequenceClassification,
    pipeline, AutoTokenizer, AutoModelForSequenceClassification
)

# Metrics
import nltk
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction, corpus_bleu
from rouge_score import rouge_scorer
from sklearn.metrics import (confusion_matrix, classification_report,
                              accuracy_score, f1_score)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"🖥️  Device: {device.upper()}")
print(f"🔥 PyTorch: {torch.__version__}")

plt.rcParams.update({'figure.dpi': 120, 'font.size': 11})
sns.set_theme(style='whitegrid', palette='muted')



"""**Section 2: LM Selection & Justification**

***Why GPT-2  and BERT?***

   **Feature                  GPT-2                       BERT**




Architecture	        Decoder-only Transformer	   Encoder-only Transformer
Training Objective	  ausal LM (CLM)	             Masked LM (MLM)
Primary Strength	    Text Generation              Language Understanding
Parameters (base)	    117M	                       110M
Released	            2019	                       2018
Open Source	          ✅ Free	                    ✅ Free










---


**Selection Rationale:** GPT-2 and BERT represent the two foundational paradigms of modern NLP. Studying both allows rigorous comparison of autoregressive generation vs. bidirectional encoding, providing complementary insights unavailable from either model alone.
"""

# ============================================================
# SECTION 2: Model Specs Table
# ============================================================
import pandas as pd
specs = {
    'Model': ['GPT-2 Small','GPT-2 Medium','BERT Base','BERT Large'],
    'Parameters': ['117M','345M','110M','340M'],
    'Layers': [12,24,12,24], 'Attn Heads': [12,16,12,16],
    'Hidden Size': [768,1024,768,1024], 'Max Tokens': [1024,1024,512,512]
}
print(pd.DataFrame(specs).to_string(index=False))
print("\n📌 We use: GPT-2 Small + BERT Base (optimal for Colab)")

"""**Section 3: GPT-2 Implementation**

GPT-2 uses a decoder-only Transformer trained on 40GB of internet text. It generates text autoregressively — predicting one token at a time from all prior tokens.
"""

